CREATE TABLE player_stats (
    name TEXT,
    team TEXT,
    pos TEXT,
    age FLOAT,
    gp INT,
    mpg FLOAT,
    usgpct FLOAT,
    topct FLOAT,
    fta INT,
    ftpct FLOAT,
    "2pa" INT,
    "2ppct" FLOAT,
    "3pa" INT,
    "3ppct" FLOAT,
    efgpct FLOAT,
    tspct FLOAT,
    ppg FLOAT,
    rpg FLOAT,
    apg FLOAT,
    spg FLOAT,
    bpg FLOAT,
    tpg FLOAT,
    p_r FLOAT,
    p_a FLOAT,
    p_r_a FLOAT,
    vi FLOAT,
    ortg FLOAT,
    drtg FLOAT,
    season TEXT
);

